// @include('../../node_modules/babel-polyfill/dist/polyfill.js')
// @include('../../node_modules/bowser/bowser.js')
// @include('../../node_modules/svg4everybody/dist/svg4everybody.js')
// @include('../../node_modules/jquery/dist/jquery.js')
// @include('../../node_modules/slick-carousel/slick/slick.js')
